name: Feature
on:
  push:
    branches:
      - feature/*

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Create Pull Request
        run: gh pr create -H main --title Merge with main --body Created by Github Action
